name: Build ZMK Firmware

on:
  workflow_dispatch:
  push:
    paths:
      - "keyboards/corne/build.yaml"
      - "keyboards/corne/config/**"

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      config_path: keyboards/corne/config
      build_matrix_path: keyboards/corne/build.yaml
