name: update flake inputs

on:
  schedule:
    - cron: '0 9 * * 1' # mondays 9am UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main

      - run: nix flake update

      - uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore(nix): update flake inputs"
          title: "chore(nix): update flake inputs"
          body: |
            automated flake.lock update.
            
            run `rebuild` locally before merging.
          branch: flake-update
          delete-branch: true
